import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { GlobalProviders } from "@/components/providers/global-providers";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Frontend Technical Test - Pago",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main className="container mx-auto py-8 px-4">
          <GlobalProviders>{children}</GlobalProviders>
        </main>
      </body>
    </html>
  );
}
